/**
 * generated by Xtext
 */
package de.schakko.xtext.ui.contentassist;

import de.schakko.xtext.ui.contentassist.AbstractAutomotiveBusDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AutomotiveBusDslProposalProvider extends AbstractAutomotiveBusDslProposalProvider {
}
