/**
 * generated by Xtext
 */
package de.schakko.xtext.validation;

import com.google.common.base.Objects;
import de.schakko.xtext.automotiveBusDsl.AutomotiveBusDslPackage;
import de.schakko.xtext.automotiveBusDsl.MessageFieldType;
import de.schakko.xtext.automotiveBusDsl.MessageInstance;
import de.schakko.xtext.automotiveBusDsl.MessageType;
import de.schakko.xtext.validation.AbstractAutomotiveBusDslValidator;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AutomotiveBusDslValidator extends AbstractAutomotiveBusDslValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public void checkGreetingStartsWithCapital(final MessageInstance messageInstance) {
    int requiredParameterCount = 0;
    MessageType _message = messageInstance.getMessage();
    EList<MessageFieldType> _fields = _message.getFields();
    for (final MessageFieldType field : _fields) {
      boolean _isIsRequired = field.isIsRequired();
      if (_isIsRequired) {
        requiredParameterCount = (requiredParameterCount + 1);
      }
    }
    boolean _and = false;
    EList<String> _params = messageInstance.getParams();
    boolean _notEquals = (!Objects.equal(_params, null));
    if (!_notEquals) {
      _and = false;
    } else {
      EList<String> _params_1 = messageInstance.getParams();
      int _size = _params_1.size();
      boolean _notEquals_1 = (_size != requiredParameterCount);
      _and = _notEquals_1;
    }
    if (_and) {
      MessageType _message_1 = messageInstance.getMessage();
      String _name = _message_1.getName();
      String _plus = ("Die Nachricht vom Typ " + _name);
      String _plus_1 = (_plus + " erwartet genau ");
      String _plus_2 = (_plus_1 + Integer.valueOf(requiredParameterCount));
      String _plus_3 = (_plus_2 + " Parameter");
      this.error(_plus_3, messageInstance, AutomotiveBusDslPackage.Literals.MESSAGE_INSTANCE__PARAMS, 100);
    }
  }
}
