/*
 * generated by Xtext
 */
package de.schakko.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AutomotiveBusDslUiModule extends de.schakko.xtext.ui.AbstractAutomotiveBusDslUiModule {
	public AutomotiveBusDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
