/*
* generated by Xtext
*/
package de.schakko.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.schakko.xtext.services.AutomotiveBusDslGrammarAccess;

public class AutomotiveBusDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AutomotiveBusDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.schakko.xtext.parser.antlr.internal.InternalAutomotiveBusDslParser createParser(XtextTokenStream stream) {
		return new de.schakko.xtext.parser.antlr.internal.InternalAutomotiveBusDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AutomotiveBusDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AutomotiveBusDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
