/*
 * generated by Xtext
 */
package de.schakko.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAutomotiveBusDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.schakko.xtext.automotiveBusDsl.AutomotiveBusDslPackage.eINSTANCE);
		return result;
	}
}
