/*
 * generated by Xtext
 */
package de.schakko.xtext.validation

import de.schakko.xtext.automotiveBusDsl.AutomotiveBusDslPackage
import de.schakko.xtext.automotiveBusDsl.MessageInstance
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class AutomotiveBusDslValidator extends AbstractAutomotiveBusDslValidator {

  	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(MessageInstance messageInstance) {
		var requiredParameterCount = 0;
		
		for (field : messageInstance.message.fields) {
			if (field.isRequired) {
				requiredParameterCount = requiredParameterCount + 1
			}
		}
		
		if (messageInstance.params != null && messageInstance.params.size != requiredParameterCount) {
			error("Die Nachricht vom Typ " + messageInstance.message.name + " erwartet genau " + requiredParameterCount + " Parameter", messageInstance, AutomotiveBusDslPackage.Literals.MESSAGE_INSTANCE__PARAMS, 100)
		}
	}
}
