/*
 * generated by Xtext
 */
package de.schakko.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AutomotiveBusDslRuntimeModule extends de.schakko.xtext.AbstractAutomotiveBusDslRuntimeModule {

}
