/*
 * generated by Xtext
 */
package de.schakko.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.schakko.xtext.ui.internal.AutomotiveBusDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AutomotiveBusDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AutomotiveBusDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AutomotiveBusDslActivator.getInstance().getInjector(AutomotiveBusDslActivator.DE_SCHAKKO_XTEXT_AUTOMOTIVEBUSDSL);
	}
	
}
